# Generated by Django 4.2.1 on 2023-06-02 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_litter', models.CharField(max_length=100)),
                ('booking_amount', models.CharField(max_length=100)),
                ('booking_datetime', models.CharField(max_length=100)),
                ('booking_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fuel_type',
            fields=[
                ('fuel_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_type_name', models.CharField(max_length=100)),
                ('fuel_type_rate', models.CharField(max_length=100)),
                ('fuel_type_datetime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('vehicles_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicles_reg_no', models.CharField(max_length=100)),
                ('vehicles_name', models.CharField(max_length=100)),
                ('vehicles_capacity', models.CharField(max_length=100)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.fuel_type')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_first_name', models.CharField(max_length=100)),
                ('u_last_name', models.CharField(max_length=100)),
                ('u_phone', models.CharField(max_length=100)),
                ('u_email', models.CharField(max_length=100)),
                ('u_licence', models.CharField(max_length=100)),
                ('u_latitude', models.CharField(max_length=100)),
                ('u_longitude', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_stock', models.CharField(max_length=100)),
                ('stock_datetime', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('rating_datetime', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_datetime', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_first_name', models.CharField(max_length=100)),
                ('d_last_name', models.CharField(max_length=100)),
                ('d_phone', models.CharField(max_length=100)),
                ('d_email', models.CharField(max_length=100)),
                ('d_licence', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('com_date', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.users')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.drivers'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.fuel_type'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.users'),
        ),
        migrations.CreateModel(
            name='assign_vehicle',
            fields=[
                ('assign_vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.drivers')),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.vehicles')),
            ],
        ),
    ]
